import type { Metadata } from "next";
import { Gabarito as Font } from "next/font/google";
import "./globals.css";
import Animation from "../components/Animation.tsx";
import Footer from "../components/Footer.tsx";

const font = Font({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Animation />
        <main>
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
